server:
  port: 8080
  servlet:
    context-path: /lawyer-app/api

spring:
  datasource:
    driver-class-name: ${MYSQL_DRIVER}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}